spring:
  mail:
    host: smtp.163.com
    username: yangfan163e@163.com
    password: TYWYAIKAPQLNSCGY
    default-encoding: UTF-8
  rabbitmq:
    host: 192.168.149.128
    port: 5672
    username: yangfan
    password: 123456
    virtual-host: yf_mq