server:
  port: 8081
spring:
  data:
    solr:
      host: http://192.168.149.128:8088/solr
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/v17?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    username: root
    password: W2zMlVXVVXuGy2O2nfTZnhw17zqF3pOJBWxAQ/IHcY5ijkgOjjtVoh7WmHlckSnBIGAofGm1npbor7LlU3zsCA==
    druid:
      initial-size: 10
      max-active: 100
      min-idle: 10
      filter:
        config:
          enabled: true
      connection-properties: config.decrypt=true;config.decrypt.key=${public-key}
dubbo:
  application:
    name: search-service
  registry:
    protocol: zookeeper
    address: 192.168.149.128:2181
  protocol:
    port: 28811
public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAImhF4IDoKcH8ObtYrMiH/QZdfmMcRsWx//E6AewSRA7fnN1v/mfZ+v/QcBOjbfXqtZsJRL8dj/Jrv/fauEkHxECAwEAAQ==
