server:
  port: 9095
dubbo:
  application:
    name: web-sso
  registry:
    protocol: zookeeper
    address: 192.168.149.128:2181
  consumer:
    check: false
#spring:
#  thymeleaf:
#    cache: false