server:
  port: 9090
dubbo:
  application:
    name: web-center
  registry:
    protocol: zookeeper
    address: 192.168.149.128:2181
  consumer:
    check: false
spring:
  thymeleaf:
    cache: false
#配置FastDFS连接信息
fdfs:
  so-timeout: 1500
  connect-timeout: 600
  pool:
    jmx-enabled: false
  thumb-image: #缩略图的大小100*100
    width: 100
    height: 100
  tracker-list: 192.168.149.128:22122

image:
  server: http://192.168.149.128/