server:
  port: 9091
dubbo:
  application:
    name: web-index
  registry:
    protocol: zookeeper
    address: 192.168.149.128:2181
  consumer:
    check: false
spring:
  thymeleaf:
    cache: false
