
server:
  port: 8084
dubbo:
  application:
    name: email-service
  registry:
    protocol: zookeeper
    address: 192.168.149.128:2181
  protocol:
    port: 28814
spring:
  rabbitmq:
    host: 192.168.149.128
    port: 5672
    username: yangfan
    password: 123456
    virtual-host: yf_mq
  mail:
    host: smtp.163.com
    username: yangfan163e@163.com
    password: TYWYAIKAPQLNSCGY
    default-encoding: UTF-8
email:
  server: yangfan163e@163.com